comment:
  layout: "header, diff, flags, components"

coverage:
  status:
    patch: off
    project:
      default:
        flags:
          - app

flag_management:
  individual_flags:
    - name: app
      paths:
        - app/
      statuses:
        - type: project
          target: auto

component_management:
  individual_components:
    - component_id: app
      name: app
      paths:
        - app

flags:
  app:
    paths:
      - app/
ignore:
  - "**/api.go"
