comment:
  layout: "header, diff, flags, components"

coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: app
      paths:
        - app/
      statuses:
        - type: project
          target: auto
          threshold: 1%

component_management:
  individual_components:
    - component_id: app
      name: app
      paths:
        - app
