version: "3"
services:

  webserver:
    image: ghcr.io/ozonophore/yoda-website
    restart: always
    environment:
      - BACKEND_HOST=frontend
      - BACKEND_PORT=8080
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "80:80"

  frontend:
    image: ghcr.io/ozonophore/yoda-web
    environment:
      - YODA_SERVER_PORT=8080
      - YODA_SERVER_MQ_URL=amqp://guest:guest@rabbitmq:5672/
      - YODA_DB_DSN=postgres://user:password@database:5432/db?sslmode=disable
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - default
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: ghcr.io/ozonophore/yoda-app
    environment:
      - YODA_DATABASE_DSN=postgres://user:password@database:5432/db?sslmode=disable
      - YODA_MQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - default
      - rabbitmq_go_net

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGUSER: user
      PGDATABASE: db
      PGPASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  migration:
    image: ghcr.io/ozonophore/yoda-migration
    tty: true
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
    depends_on:
      - database
    networks:
      - default

networks:
  default:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge
volumes:
  data:
    external: true
