version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5