// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOwnerMarketplace = "owner_marketplace"

// OwnerMarketplace mapped from table <owner_marketplace>
type OwnerMarketplace struct {
	OwnerCode string  `gorm:"column:owner_code;primaryKey" json:"owner_code"`
	Source    string  `gorm:"column:source;primaryKey" json:"source"`
	Host      string  `gorm:"column:host;not null" json:"host"`
	Password  *string `gorm:"column:password" json:"password"`
	ClientID  *string `gorm:"column:client_id" json:"client_id"`
}

// TableName OwnerMarketplace's table name
func (*OwnerMarketplace) TableName() string {
	return TableNameOwnerMarketplace
}
