// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTlgQueue = "tlg_queue"

const (
	TlgMessageStatusCreated  = "CREATED"
	TlgMessageStatusPending   = "PENDING"
	TlgMessageStatusComplited = "COMPLETED"
	TlgMessageStatusError     = "ERROR"
)

// TlgMessage mapped from table <tlg_queue>
type TlgMessage struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChatID       int64      `gorm:"column:chat_id;primaryKey" json:"chat_id"`                         // Идентификатор чата
	ChatType     string     `gorm:"column:chat_type;not null" json:"chat_type"`                       // Тип чата
	MessageID    int        `gorm:"column:message_id;primaryKey" json:"message_id"`                   // Идентификатор сообщения
	Message      *string    `gorm:"column:message" json:"message"`                                    // Текст сообщения
	MessageDate  time.Time  `gorm:"column:message_date;not null" json:"message_date"`                 // Дата и время отправки сообщения
	ResponseDate *time.Time `gorm:"column:response_date" json:"response_date"`                        // Дата и время получения ответа на сообщение
	Status       string     `gorm:"column:status;default:'CREATED'::character varying" json:"status"` // Статус сообщения
}

// TableName TlgMessage's table name
func (*TlgMessage) TableName() string {
	return TableNameTlgQueue
}
