version: "3.8"
services:
  database:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pdb
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - default
  migration:
    image: migrate/migrate
    build:
        context: ../migration
        dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: pdb
    links:
      - database
    volumes:
      - ../migration/changelog:/migrations/changelog
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
  mockServer:
    image: mockserver/mockserver:5.14.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /mockserver/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mockserver/*.json
    volumes:
      - type: bind
        source: ./mockserver
        target: /mockserver

networks:
  default:
    driver: bridge
