## Build
FROM golang:1.20 AS build

WORKDIR /app

COPY server/go.work ./
COPY server/go.work.sum ./
COPY server/common ./common
COPY server/webapp ./webapp
COPY server/app ./app
COPY openapi /openapi
RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
RUN go mod download

WORKDIR /app/webapp
RUN make build

## Deploy
FROM centos:7

WORKDIR /app

COPY --from=build /app/webapp/build/webapp-amd64-linux /

EXPOSE 8080

ENTRYPOINT ["/webapp-amd64-linux"]
