// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameJobOwner = `"ml"."job_owner"`

// JobOwner mapped from table <job_owner>
type JobOwner struct {
	JobID     int                `gorm:"column:job_id;primaryKey" json:"job_id"`
	OwnerCode string             `gorm:"column:owner_code;primaryKey" json:"owner_code"`
}

// TableName JobOwner's table name
func (*JobOwner) TableName() string {
	return TableNameJobOwner
}
