// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLogLoad = `"ml"."log_load"`

// LogLoad mapped from table <log_load>
type LogLoad struct {
	TransactionID int64   `gorm:"column:transaction_id;primaryKey" json:"transaction_id"` // Идентификатор транзакции
	OwnerCode     string  `gorm:"column:owner_code;primaryKey" json:"owner_code"`         // Код владельца
	Source        string  `gorm:"column:source;primaryKey" json:"source"`                 // Источник данных
	Description   *string `gorm:"column:description" json:"description"`                  // Описание
	Status        string  `gorm:"column:status;not null" json:"status"`                   // Статус BEGIN|COMPLETED|ERROR
}

// TableName LogLoad's table name
func (*LogLoad) TableName() string {
	return TableNameLogLoad
}
