// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMarketplace = "marketplace"

// Marketplace mapped from table <marketplace>
type Marketplace struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`               // ID
	Name      string    `gorm:"column:name;not null" json:"name"`             // Name
	Article   *string   `gorm:"column:article" json:"article"`                // Article
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"` // Updated at
}

// TableName Marketplace's table name
func (*Marketplace) TableName() string {
	return TableNameMarketplace
}
