// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganisation = "organisation"

// Organisation mapped from table <organisation>
type Organisation struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`           // Идентификатор организации
	Name     string    `gorm:"column:name" json:"name"`                  // Наименование организации
	Inn      *string   `gorm:"column:inn" json:"inn"`                    // ИНН организации
	Kpp      *string   `gorm:"column:kpp" json:"kpp"`                    // КПП организации
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"updateAt"` // Дата и время обновления записи
}

// TableName Organisation's table name
func (*Organisation) TableName() string {
	return TableNameOrganisation
}
