// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportDetailByPeriod = `dl."report_detail_by_period"`

// ReportDetailByPeriod mapped from table <report_detail_by_period>
type ReportDetailByPeriod struct {
	ID                       int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransactionID            int64      `gorm:"column:transaction_id;not null" json:"transaction_id"`
	Source                   string     `gorm:"column:source;not null" json:"source"`
	OwnerCode                string     `gorm:"column:owner_code;not null" json:"owner_code"`
	AcquiringBank            *string    `gorm:"column:acquiring_bank" json:"acquiring_bank"`
	AcquiringFee             *float64   `gorm:"column:acquiring_fee" json:"acquiring_fee"`
	AdditionalPayment        *float64   `gorm:"column:additional_payment" json:"additional_payment"`
	Barcode                  *string    `gorm:"column:barcode" json:"barcode"`
	BonusTypeName            *string    `gorm:"column:bonus_type_name" json:"bonus_type_name"`
	BrandName                *string    `gorm:"column:brand_name" json:"brand_name"`
	CommissionPercent        *float64   `gorm:"column:commission_percent" json:"commission_percent"`
	CreateDt                 *time.Time `gorm:"column:create_dt" json:"create_dt"`
	DateFrom                 *time.Time `gorm:"column:date_from" json:"date_from"`
	DateTo                   *time.Time `gorm:"column:date_to" json:"date_to"`
	DeclarationNumber        *string    `gorm:"column:declaration_number" json:"declaration_number"`
	DeliveryAmount           *int64     `gorm:"column:delivery_amount" json:"delivery_amount"`
	DeliveryRub              *float64   `gorm:"column:delivery_rub" json:"delivery_rub"`
	DocNumber                *string    `gorm:"column:doc_number" json:"doc_number"`
	DocTypeName              *string    `gorm:"column:doc_type_name" json:"doc_type_name"`
	GiBoxTypeName            *string    `gorm:"column:gi_box_type_name" json:"gi_box_type_name"`
	GiID                     *int64     `gorm:"column:gi_id" json:"gi_id"`
	Kiz                      *string    `gorm:"column:kiz" json:"kiz"`
	NmID                     *int64     `gorm:"column:nm_id" json:"nm_id"`
	OfficeName               *string    `gorm:"column:office_name" json:"office_name"`
	OrderDt                  *time.Time `gorm:"column:order_dt" json:"order_dt"`
	Penalty                  *float64   `gorm:"column:penalty" json:"penalty"`
	PpvzForPay               *float64   `gorm:"column:ppvz_for_pay" json:"ppvz_for_pay"`
	PpvzInn                  *string    `gorm:"column:ppvz_inn" json:"ppvz_inn"`
	PpvzKvwPrc               *float64   `gorm:"column:ppvz_kvw_prc" json:"ppvz_kvw_prc"`
	PpvzKvwPrcBase           *float64   `gorm:"column:ppvz_kvw_prc_base" json:"ppvz_kvw_prc_base"`
	PpvzOfficeID             *int64     `gorm:"column:ppvz_office_id" json:"ppvz_office_id"`
	PpvzOfficeName           *string    `gorm:"column:ppvz_office_name" json:"ppvz_office_name"`
	PpvzReward               *float64   `gorm:"column:ppvz_reward" json:"ppvz_reward"`
	PpvzSalesCommission      *float64   `gorm:"column:ppvz_sales_commission" json:"ppvz_sales_commission"`
	PpvzSppPrc               *float64   `gorm:"column:ppvz_spp_prc" json:"ppvz_spp_prc"`
	PpvzSupplierID           *int64     `gorm:"column:ppvz_supplier_id" json:"ppvz_supplier_id"`
	PpvzSupplierName         *string    `gorm:"column:ppvz_supplier_name" json:"ppvz_supplier_name"`
	PpvzVw                   *float64   `gorm:"column:ppvz_vw" json:"ppvz_vw"`
	PpvzVwNds                *float64   `gorm:"column:ppvz_vw_nds" json:"ppvz_vw_nds"`
	ProductDiscountForReport *float64   `gorm:"column:product_discount_for_report" json:"product_discount_for_report"`
	Quantity                 *int64     `gorm:"column:quantity" json:"quantity"`
	RealizationreportID      *int64     `gorm:"column:realizationreport_id" json:"realizationreport_id"`
	RetailAmount             *float64   `gorm:"column:retail_amount" json:"retail_amount"`
	RetailPrice              *float64   `gorm:"column:retail_price" json:"retail_price"`
	RetailPriceWithdiscRub   *float64   `gorm:"column:retail_price_withdisc_rub" json:"retail_price_withdisc_rub"`
	ReturnAmount             *int64     `gorm:"column:return_amount" json:"return_amount"`
	Rid                      *int64     `gorm:"column:rid" json:"rid"`
	RrDt                     *time.Time `gorm:"column:rr_dt" json:"rr_dt"`
	RrdID                    *int64     `gorm:"column:rrd_id" json:"rrd_id"`
	SaName                   *string    `gorm:"column:sa_name" json:"sa_name"`
	SaleDt                   *time.Time `gorm:"column:sale_dt" json:"sale_dt"`
	SalePercent              *int64     `gorm:"column:sale_percent" json:"sale_percent"`
	ShkID                    *int64     `gorm:"column:shk_id" json:"shk_id"`
	SiteCountry              *string    `gorm:"column:site_country" json:"site_country"`
	Srid                     *string    `gorm:"column:srid" json:"srid"`
	StickerID                *string    `gorm:"column:sticker_id" json:"sticker_id"`
	SubjectName              *string    `gorm:"column:subject_name" json:"subject_name"`
	SupplierOperName         *string    `gorm:"column:supplier_oper_name" json:"supplier_oper_name"`
	SupplierPromo            *float64   `gorm:"column:supplier_promo" json:"supplier_promo"`
	SuppliercontractCode     *string    `gorm:"column:suppliercontract_code" json:"suppliercontract_code"`
	TsName                   *string    `gorm:"column:ts_name" json:"ts_name"`
	ItemID                   *string    `gorm:"column:item_id" json:"item_id"`
	BarcodeID                *string    `gorm:"column:barcode_id" json:"barcode_id"`
	Message                  *string    `gorm:"column:message" json:"message"`
}

// TableName ReportDetailByPeriod's table name
func (*ReportDetailByPeriod) TableName() string {
	return TableNameReportDetailByPeriod
}
