database:
  logging_level: info
  dsn: postgresql://user:password@212.48.159.224:5432/db
#  dsn: postgres://user:password@localhost:5432/db
timeout: 60
mq:
  url: amqp://guest:guest@localhost:5672/
  consumer: yoda-server-consumer
  publisher: yoda-publisher
#ozon:
#  host: http://localhost:1080/ozon
logging_level: debug