database:
  dsn: postgres://user:password@localhost:5432/db
  logging_level: error #info, error, warn
timeout: 60
mq:
  url: amqp://guest:guest@localhost:5672/
  consumer: yoda-server-consumer
  publisher: yoda-publisher
#ozon:
#  host: http://localhost:1080/ozon
logging_level: debug