database:
#  logging_level: info
  dsn: postgresql://user:password@212.48.159.224:5432/db
#  dsn: postgres://user:password@localhost:5432/db
logging_level: debug
token: "5912839636:AAHa3HGr2eJCUGf6KzrmxCcys1tsGAcmE6I"