server:
  port: 8080
logging_level: DEBUG
telegramBot:
  logging_level: DEBUG
database:
  dsn: postgres://user:password@localhost:5432/db
mq:
  url: amqp://guest:guest@localhost:5672/
  read_queue: yoda-server
  write_queue: yoda-client
