name: Go

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20.x"]
        include:
          - go: 1.20.x
            latest: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Download Dependencies
        run: |
          cd server/app && go mod download

      - name: Test
        run: cd server/app && make test

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          flags: app
