name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
      - uses: bhowell2/github-substring-action@v1.0.0
        name: Get the version number
        id: get-version
        with:
          value: ${{ steps.bump-semver.outputs.new_version }}
          index_of_str: v
      - name: Echo new version
        run: echo ${{ steps.get-version.outputs.substring }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set working directory website
        run: cd website
      - name: Build and push website
        uses: docker/build-push-action@v4
        with:
          context: ..
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/yoda-website:latest,ghcr.io/${{ github.actor }}/yoda-website:${{ steps.get-version.outputs.substring }}

      - name: Set working directory web
        run: cd server
      - name: Build and push web
        uses: docker/build-push-action@v4
        with:
          context: ..
          file: Dockerfile.web
          push: true
          tags: ghcr.io/${{ github.actor }}/yoda-web:latest,ghcr.io/${{ github.actor }}/yoda-web:${{ steps.get-version.outputs.substring }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          name: ${{ steps.bump-semver.outputs.new_version }}
          body: |
            Release ${{ steps.bump-semver.outputs.new_version }}