version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - YODA_PORT=8080
      - YODA_DB_DSN=postgresql://user:password@212.48.159.224:5432/db
    ports:
      - "8088:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
